<?php

namespace ASK\MenuBundle\Repository;

use ASK\MenuBundle\Entity\Menu;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Gedmo\Exception\InvalidArgumentException;
use Gedmo\Tool\Wrapper\EntityWrapper;
/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends NestedTreeRepository // \Doctrine\ORM\EntityRepository
{
    public function up(Menu $node)
    {
        $parent = $node->getParent();
        dump($parent); die;
    }
}


